name: automerge
on:
  pull_request: 
    branches:
      - 'master'
    types:
      - opened
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
