name: pull_request
on:
  pull_request: 
    branches:
      - '?*\-api\/master'
    types:
      closed
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: master
          author-name: github-actions[bot]
          author-email: 41898282+github-actions[bot]@users.noreply.github.com
          committer-name: GitHub
          committer-email: noreply@github.com    
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}" 
