name: automerge
on:
  pull_request: 
    branches:
      - '?*\-api\/master'
    types:
      - synchronize
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "auto merge from api/master"
          MERGE_LABELS: ""
